// File: src/utils/mock-data.ts

import { WorkloadType } from "@/types/workload";
import { WorkloadDetail, Rule, Server } from "@/types/workload-detail";

export const getMockWorkloadDetail = (id: string): WorkloadDetail => ({
  id: parseInt(id),
  name: `workload_${id}`,
  display_name: `Production Workload ${id}`,
  description:
    "Critical production workload handling customer data and business operations. Requires high security compliance and monitoring.",
  workload_type: WorkloadType.APP,
  is_active: true,
  created_at: "2024-01-15T10:30:00Z",
  updated_at: "2024-08-15T14:20:00Z",
  created_by: "admin@company.com",
  compliance_standard: "ISO 27001",
  server_count: 12,
  rule_count: 18,
  last_scan: "2024-08-18T08:00:00Z",
  scan_status: "success",
});

export const getMockRules = (): Rule[] => [
  {
    id: 1,
    name: "Password Policy Enforcement",
    description: "Ensure strong password policies are implemented",
    severity: "high",
    category: "Authentication",
    condition: "password_length >= 12 AND password_complexity == true",
    action: "Block access if password policy not met",
    is_enabled: true,
    last_execution: "2024-08-18T08:00:00Z",
    execution_status: "success",
  },
  {
    id: 2,
    name: "SSL/TLS Configuration",
    description: "Verify secure SSL/TLS configuration",
    severity: "critical",
    category: "Network Security",
    condition: "ssl_version >= 'TLSv1.2' AND weak_ciphers == false",
    action: "Disable weak SSL/TLS configurations",
    is_enabled: true,
    last_execution: "2024-08-18T08:05:00Z",
    execution_status: "success",
  },
  {
    id: 3,
    name: "File Permission Check",
    description: "Monitor sensitive file permissions",
    severity: "medium",
    category: "File System",
    condition: "file_permissions NOT LIKE '%777%'",
    action: "Alert and log permission violations",
    is_enabled: false,
    last_execution: "2024-08-17T22:00:00Z",
    execution_status: "failed",
  },
  {
    id: 4,
    name: "Service Account Monitoring",
    description: "Track service account activities",
    severity: "medium",
    category: "Access Control",
    condition: "service_account_activity == 'abnormal'",
    action: "Generate security alert",
    is_enabled: true,
    last_execution: "2024-08-18T07:45:00Z",
    execution_status: "pending",
  },
  {
    id: 5,
    name: "Database Encryption",
    description: "Ensure database encryption at rest",
    severity: "high",
    category: "Data Protection",
    condition: "database_encryption == true AND key_rotation <= 90_days",
    action: "Force encryption if not enabled",
    is_enabled: true,
    last_execution: "2024-08-18T06:30:00Z",
    execution_status: "success",
  },
  {
    id: 6,
    name: "Anti-Malware Configuration",
    description:
      "Ensure antimalware software is properly configured and updated",
    severity: "critical",
    category: "Security Software",
    condition: "antimalware_enabled == true AND definitions_age <= 1_day",
    action: "Update definitions and enable real-time protection",
    is_enabled: true,
    last_execution: "2024-08-18T07:30:00Z",
    execution_status: "success",
  },
  {
    id: 7,
    name: "Firewall Rules Validation",
    description: "Validate firewall rules and configurations",
    severity: "high",
    category: "Network Security",
    condition: "firewall_enabled == true AND unnecessary_ports_closed == true",
    action: "Block unnecessary ports and enable firewall",
    is_enabled: true,
    last_execution: "2024-08-18T07:15:00Z",
    execution_status: "success",
  },
  {
    id: 8,
    name: "User Account Control",
    description: "Monitor user account privileges and access",
    severity: "medium",
    category: "Access Control",
    condition: "admin_accounts <= 5 AND guest_account_disabled == true",
    action: "Disable unnecessary admin accounts",
    is_enabled: true,
    last_execution: "2024-08-18T06:45:00Z",
    execution_status: "pending",
  },
  {
    id: 9,
    name: "System Updates Check",
    description: "Ensure system updates are applied regularly",
    severity: "high",
    category: "System Maintenance",
    condition: "last_update_age <= 30_days AND auto_update_enabled == true",
    action: "Apply pending updates and enable auto-update",
    is_enabled: true,
    last_execution: "2024-08-18T06:00:00Z",
    execution_status: "success",
  },
  {
    id: 10,
    name: "Log Monitoring",
    description: "Monitor system and security logs for anomalies",
    severity: "medium",
    category: "Monitoring",
    condition: "log_size < 100MB AND failed_login_attempts <= 5",
    action: "Archive logs and investigate failed attempts",
    is_enabled: true,
    last_execution: "2024-08-18T05:30:00Z",
    execution_status: "success",
  },
  {
    id: 11,
    name: "Remote Access Security",
    description: "Secure remote access configurations",
    severity: "critical",
    category: "Network Security",
    condition: "rdp_disabled == true OR rdp_nla_enabled == true",
    action: "Disable RDP or enable Network Level Authentication",
    is_enabled: false,
    last_execution: "2024-08-17T20:00:00Z",
    execution_status: "failed",
  },
  {
    id: 12,
    name: "Backup Verification",
    description: "Verify backup systems are functioning properly",
    severity: "high",
    category: "Data Protection",
    condition: "backup_status == 'success' AND backup_age <= 7_days",
    action: "Verify backup integrity and schedule",
    is_enabled: true,
    last_execution: "2024-08-18T04:00:00Z",
    execution_status: "success",
  },
  {
    id: 13,
    name: "Network Segmentation",
    description: "Ensure proper network segmentation is implemented",
    severity: "medium",
    category: "Network Security",
    condition:
      "vlan_separation == true AND inter_vlan_rules_configured == true",
    action: "Configure network segmentation rules",
    is_enabled: true,
    last_execution: "2024-08-18T03:30:00Z",
    execution_status: "pending",
  },
  {
    id: 14,
    name: "Privileged Access Management",
    description: "Monitor and control privileged access",
    severity: "critical",
    category: "Access Control",
    condition:
      "sudo_usage_logged == true AND privileged_sessions_monitored == true",
    action: "Enable privileged access monitoring",
    is_enabled: true,
    last_execution: "2024-08-18T03:00:00Z",
    execution_status: "success",
  },
  {
    id: 15,
    name: "Application Security",
    description: "Verify application security configurations",
    severity: "high",
    category: "Application Security",
    condition: "secure_headers_enabled == true AND input_validation == true",
    action: "Enable security headers and input validation",
    is_enabled: true,
    last_execution: "2024-08-18T02:30:00Z",
    execution_status: "success",
  },
  {
    id: 16,
    name: "Endpoint Detection",
    description: "Monitor endpoints for suspicious activities",
    severity: "medium",
    category: "Monitoring",
    condition: "edr_agent_running == true AND threat_detected == false",
    action: "Investigate detected threats",
    is_enabled: false,
    last_execution: "2024-08-17T18:00:00Z",
    execution_status: "failed",
  },
  {
    id: 17,
    name: "Data Loss Prevention",
    description: "Prevent unauthorized data exfiltration",
    severity: "high",
    category: "Data Protection",
    condition:
      "dlp_policy_active == true AND data_classification == 'classified'",
    action: "Block unauthorized data transfers",
    is_enabled: true,
    last_execution: "2024-08-18T02:00:00Z",
    execution_status: "success",
  },
  {
    id: 18,
    name: "Vulnerability Assessment",
    description: "Regular vulnerability scanning and assessment",
    severity: "medium",
    category: "Security Assessment",
    condition: "last_scan_age <= 7_days AND critical_vulns == 0",
    action: "Schedule vulnerability scan",
    is_enabled: true,
    last_execution: "2024-08-18T01:30:00Z",
    execution_status: "pending",
  },
];

export const getMockServers = (): Server[] => [
  {
    id: 1,
    name: "prod-web-01",
    ip_address: "10.0.1.10",
    os: "Ubuntu 22.04 LTS",
    status: "online",
    compliance_score: 95,
    last_check: "2024-08-18T08:00:00Z",
  },
  {
    id: 2,
    name: "prod-web-02",
    ip_address: "10.0.1.11",
    os: "Ubuntu 22.04 LTS",
    status: "online",
    compliance_score: 92,
    last_check: "2024-08-18T08:00:00Z",
  },
  {
    id: 3,
    name: "prod-db-01",
    ip_address: "10.0.2.10",
    os: "CentOS 8",
    status: "online",
    compliance_score: 98,
    last_check: "2024-08-18T08:00:00Z",
  },
  {
    id: 4,
    name: "prod-cache-01",
    ip_address: "10.0.3.10",
    os: "Redis 7.0",
    status: "maintenance",
    compliance_score: 85,
    last_check: "2024-08-17T23:30:00Z",
  },
  {
    id: 5,
    name: "prod-api-01",
    ip_address: "10.0.1.20",
    os: "Ubuntu 22.04 LTS",
    status: "offline",
    compliance_score: 75,
    last_check: "2024-08-17T18:00:00Z",
  },
];
